backend:
  name: github
  repo: integrityph/abc
  branch: main
  base_url: https://oauth-crm.ngrok.io/
  auth_endpoint: /auth
  structure: multiple_folders
media_folder: "public/static/images/uploads"
public_folder: "static/images/uploads"
collections:
  - name: "solutions"
    label: "Solutions"
    folder: "src/content/solutions"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "List Title", name: "list_title", widget: "string" }
      - { label: "List Sub Title", name: "list_sub_title", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - { label: "Url", name: "url", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string" }
      - label: "Logo Small"
        name: "logo_small"
        widget: "object"
        fields:
          - { label: "Url", name: "url", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string" }
      - label: "Logo Large"
        name: "logo_large"
        widget: "object"
        fields:
          - { label: "Url", name: "url", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string" }
      - label: "Parallax"
        name: "parallax"
        widget: "object"
        fields:
          - { label: "Url", name: "url", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string" }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Caption", name: "caption", widget: "string", required: false }
          - { label: "Source", name: "src", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "View Title", name: "view_title", widget: "string" }
      - { label: "View Sub Title", name: "view_sub_title", widget: "string", required: false }
      - { label: "View Text", name: "view_text", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Custom Action Name", name: "custom_action_name", widget: "string", required: false }
      - { label: "Custom Action URL", name: "custom_action_url", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "services"
    label: "Services"
    folder: "src/content/services"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - label: "Image"
        name: "image"
        widget: "object"
        collapsed: true
        fields: 
          - { label: "Source", name: "src", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "about"
    label: "About"
    folder: "src/content/about"
    create: true
    fields:
      - { label: "File Name", name: "title", widget: "string", required: true }
      - label: "Values"
        name: "values"
        widget: "list"
        collapsed: true
        fields: 
        - { label: "Title", name: "title", widget: "string", required: true }
        - { label: "Description", name: "description", widget: "string", required: true }
      - label: "Gallery Image"
        name: "gallery_image"
        widget: "list"
        collapsed: true
        fields: 
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Caption", name: "caption", widget: "string", required: false }
          - { label: "Source", name: "src", widget: "image", required: false }
          - { label: "Alt", name: "alt", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "careers"
    label: "Careers"
    folder: "src/content/careers"
    create: true
    fields:
      - { label: "Career", name: "title", widget: "string", required: true }
      - label: "Image"
        name: "image"
        widget: "object"
        collapsed: false
        fields: 
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Caption", name: "caption", widget: "string", required: false }
          - { label: "Source", name: "src", widget: "image", required: true }
          - { label: "Alt", name: "alt", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: false }
